# Generated by Django 5.0.3 on 2024-03-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes', to='menu.cook'),
        ),
    ]
