# Generated by Django 5.0.3 on 2024-03-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_cooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(related_name='dishes', to='menu.cook'),
        ),
    ]
